### ISSUE TITLE
Failure to launch ModuleNotFoundError: No module named 'fuzzywuzzy'

### ISSUE THREAD

**Issue by abienz** [jonian/kickoff-player#12]
Hi I'm running on Arch Linux, for a while now without issue.

Just now trying it out I get the following error in the command line.

```kickoff-player
Traceback (most recent call last):
  File "/usr/bin/kickoff-player", line 19, in <module>
    from apis.streams import StreamsApi
  File "/opt/kickoff-player-git/apis/streams.py", line 3, in <module>
    from fuzzywuzzy import fuzz```

**Comment by jonian** [comment]
You need to rebuild all the python packages from AUR due to python update from 3.7 to 3.8.
