### ISSUE TITLE
No module named 'playhouse'

### ISSUE THREAD

**Issue by hitagiend** [jonian/kickoff-player#13]
when I try to launch on my laptop it says
```
Traceback (most recent call last):
  File "/usr/bin/kickoff-player", line 12, in <module>
    from handlers.data import DataHandler, StaticStream
  File "/opt/kickoff-player-git/handlers/data.py", line 3, in <module>
    from playhouse.sqlite_ext import CharField, IntegerField, BooleanField
ModuleNotFoundError: No module named 'playhouse'
```

**Comment by jonian** [comment]
You have to install all dependencies mentioned in the readme. The `playhouse` module is part of `python-peewee`.
